"use client";
import {useActionState,useState} from "react";
import {createInvoiceAction,createDirectInvoiceAction} from "../actions";
import Decimal from "decimal.js";
export type OrderWithClient={id:string;quantity:number;created_at:string;product_spec:unknown;clients:{name:string;type:string;price_tier:string|null}|null};
export type ClientSimple={id:string;name:string;phone:string|null;type:string;price_tier:string|null};
type Row={key:number;capacity:string;quantity:number;unitPrice:number};
const blank=():Row=>({key:Date.now()+Math.random(),capacity:"",quantity:1,unitPrice:0});
function total(rows:Row[],shipping:number,discount:number){return rows.reduce((sum,row)=>sum.plus(new Decimal(row.quantity||0).times(row.unitPrice||0)),new Decimal(0)).plus(shipping||0).minus(discount||0).toDecimalPlaces(2).toNumber();}
function orderRows(order:OrderWithClient):Row[]{
 const source=Array.isArray(order.product_spec)?order.product_spec:[];
 const rows=source.filter((v):v is {capacity:string;quantity:number}=>!!v&&typeof v==="object"&&typeof v.capacity==="string"&&Number.isInteger(v.quantity)&&v.quantity>0).map((v,i)=>({key:i,capacity:v.capacity,quantity:v.quantity,unitPrice:0}));
 return rows.length&&rows.reduce((n,row)=>n+row.quantity,0)===order.quantity?rows:[{key:0,capacity:`أمر شغل ${order.id.slice(0,8)}`,quantity:order.quantity,unitPrice:0}];
}
function LineEditor({rows,setRows,lockedQuantity=false}:{rows:Row[];setRows:React.Dispatch<React.SetStateAction<Row[]>>;lockedQuantity?:boolean}){
 const update=(key:number,patch:Partial<Row>)=>setRows(current=>current.map(row=>row.key===key?{...row,...patch}:row));
 return <section className="space-y-3"><div className="flex items-center justify-between"><h3 className="text-lg font-bold">بنود الفاتورة</h3>{!lockedQuantity&&<button type="button" onClick={()=>setRows(current=>[...current,blank()])} className="rounded border px-3 py-2 text-blue-700">إضافة بند</button>}</div>
  {rows.map(row=><div key={row.key} className="grid gap-3 rounded-xl border bg-slate-50 p-4 sm:grid-cols-[2fr_1fr_1fr_auto]"><label className="text-sm">الصنف / السعة<input required name="capacity[]" value={row.capacity} onChange={e=>update(row.key,{capacity:e.target.value})} maxLength={300} className="mt-1 w-full rounded border p-2"/></label><label className="text-sm">الكمية<input required type="number" min="1" step="1" name="quantity[]" value={row.quantity} onChange={e=>update(row.key,{quantity:Number(e.target.value)})} readOnly={lockedQuantity} className="mt-1 w-full rounded border p-2"/></label><label className="text-sm">سعر الوحدة<input required type="number" min="0" step="0.01" name="unit_price[]" value={row.unitPrice} onChange={e=>update(row.key,{unitPrice:Number(e.target.value)})} className="mt-1 w-full rounded border p-2"/></label><button type="button" disabled={lockedQuantity||rows.length===1} onClick={()=>setRows(current=>current.filter(item=>item.key!==row.key))} className="self-end rounded border px-3 py-2 text-red-700 disabled:opacity-30">حذف</button></div>)}
 </section>;
}
function Costs({shipping,setShipping,discount,setDiscount,rows}:{shipping:number;setShipping:(v:number)=>void;discount:number;setDiscount:(v:number)=>void;rows:Row[]}){
 return <><div className="grid gap-4 sm:grid-cols-2"><label>النقل والمصاريف<input name="shipping_amount" type="number" min="0" step="0.01" value={shipping} onChange={e=>setShipping(Number(e.target.value))} className="mt-1 w-full rounded border p-2"/></label><label>الخصم<input name="discount_amount" type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(Number(e.target.value))} className="mt-1 w-full rounded border p-2"/></label></div><label className="block">ملاحظات الفاتورة<textarea name="notes" rows={3} maxLength={2000} className="mt-1 w-full rounded border p-2"/></label><p className="text-xl font-bold">الإجمالي المحسوب: {total(rows,shipping,discount).toLocaleString("ar-EG")} ج.م</p>{total(rows,shipping,discount)<0&&<p role="alert" className="text-red-700">الخصم يتجاوز قيمة البنود والمصاريف.</p>}</>;
}
export default function InvoiceForm({orders,clients}:{orders:OrderWithClient[];clients:ClientSimple[]}){
 const [tab,setTab]=useState<"order"|"direct">("order");
 const [orderState,orderAction,orderPending]=useActionState(createInvoiceAction,null);
 const [directState,directAction,directPending]=useActionState(createDirectInvoiceAction,null);
 const [orderId,setOrderId]=useState("");const [orderLines,setOrderLines]=useState<Row[]>([]);
 const [directLines,setDirectLines]=useState<Row[]>([blank()]);
 const [orderShipping,setOrderShipping]=useState(0),[orderDiscount,setOrderDiscount]=useState(0);
 const [directShipping,setDirectShipping]=useState(0),[directDiscount,setDirectDiscount]=useState(0);
 const [clientMode,setClientMode]=useState<"existing"|"new">("existing");
 return <div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="grid grid-cols-2 border-b"><button type="button" onClick={()=>setTab("order")} className={`p-4 font-bold ${tab==="order"?"bg-blue-50 text-blue-800":"text-slate-500"}`}>فاتورة أمر شغل</button><button type="button" onClick={()=>setTab("direct")} className={`p-4 font-bold ${tab==="direct"?"bg-blue-50 text-blue-800":"text-slate-500"}`}>فاتورة بيع مباشر</button></div>
 {tab==="order"?<form action={orderAction} className="space-y-6 p-6"><label className="block">أمر الشغل<select name="order_id" required value={orderId} onChange={e=>{const id=e.target.value;setOrderId(id);const order=orders.find(o=>o.id===id);setOrderLines(order?orderRows(order):[]);}} className="mt-1 w-full rounded border p-2"><option value="">اختر أمر الشغل</option>{orders.map(order=><option key={order.id} value={order.id}>{order.clients?.name??"عميل"} — {order.quantity} خزان — {new Date(order.created_at).toLocaleDateString("ar-EG")}</option>)}</select></label>{orders.length===0&&<p>لا توجد أوامر شغل جاهزة للفوترة. استخدم البيع المباشر.</p>}{orderId&&<LineEditor rows={orderLines} setRows={setOrderLines} lockedQuantity/>}<Costs rows={orderLines} shipping={orderShipping} setShipping={setOrderShipping} discount={orderDiscount} setDiscount={setOrderDiscount}/>{orderState?.message&&<p role="alert" className="text-red-700">{orderState.message}</p>}<button disabled={orderPending||!orderId||total(orderLines,orderShipping,orderDiscount)<0} className="rounded bg-blue-700 px-5 py-3 font-bold text-white disabled:opacity-40">{orderPending?"جارٍ الإصدار…":"إصدار الفاتورة"}</button></form>
 :<form action={directAction} className="space-y-6 p-6"><div className="flex gap-4"><label><input type="radio" checked={clientMode==="existing"} onChange={()=>setClientMode("existing")}/> عميل حالي</label><label><input type="radio" checked={clientMode==="new"} onChange={()=>setClientMode("new")}/> عميل جديد</label></div>{clientMode==="existing"?<label className="block">العميل<select required name="client_id" className="mt-1 w-full rounded border p-2"><option value="">اختر العميل</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>:<div className="grid gap-4 sm:grid-cols-3"><label>اسم العميل<input required name="client_name" minLength={3} className="mt-1 w-full rounded border p-2"/></label><label>نوع العميل<select name="client_type" className="mt-1 w-full rounded border p-2"><option value="individual">فرد</option><option value="trader">تاجر</option><option value="contractor">مقاول</option><option value="company">شركة</option><option value="office">مكتب</option></select></label><label>الهاتف<input name="client_phone" className="mt-1 w-full rounded border p-2"/></label></div>}
 <LineEditor rows={directLines} setRows={setDirectLines}/><Costs rows={directLines} shipping={directShipping} setShipping={setDirectShipping} discount={directDiscount} setDiscount={setDirectDiscount} /><label className="block">المدفوع مقدمًا<input name="paid_amount" type="number" required min="0" max={Math.max(total(directLines,directShipping,directDiscount),0)} step="0.01" defaultValue="0" className="mt-1 w-full rounded border p-2"/></label>{directState?.message&&<p role="alert" className="text-red-700">{directState.message}</p>}<button disabled={directPending||total(directLines,directShipping,directDiscount)<0} className="rounded bg-blue-700 px-5 py-3 font-bold text-white disabled:opacity-40">{directPending?"جارٍ الإصدار…":"إصدار الفاتورة المباشرة"}</button></form>}
 </div>;
}