"use client";
import {linkExistingMember} from './link-action';
import {useActionState} from 'react';
import {saveMember,createMember} from './actions';
const options=[['sales','المبيعات والتحصيل'],['production','الإنتاج والخامات'],['attendance','الحضور فقط دون الرواتب'],['payroll','العمال والرواتب'],['suppliers','حسابات الموردين']];
type Member={user_id:string;email:string;role:string;permissions:string[];active:boolean};
export function MemberForm({member}:{member:Member}){
 const [state,action,pending]=useActionState(saveMember,undefined);
 return <form action={action} className="border rounded p-4 space-y-3"><h3 dir="ltr">{member.email}</h3><input type="hidden" name="id" value={member.user_id}/><label>الدور <select name="role" defaultValue={member.role} className="border p-2"><option value="employee">موظف</option><option value="admin">مدير</option></select></label><label className="block"><input type="checkbox" name="active" defaultChecked={member.active}/> الحساب نشط</label><p>صلاحيات الموظف: عرض وتسجيل في الأقسام المختارة. المدير يملك جميع الأقسام.</p>{options.map(([id,label])=><label className="block" key={id}><input name="permissions" type="checkbox" value={id} defaultChecked={member.permissions.includes(id)}/> {label}</label>)}{state?.message&&<p role={state.success?'status':'alert'}>{state.message}</p>}<button disabled={pending} className="border p-2">حفظ الصلاحيات</button></form>;
}
export function NewMemberForm(){const [state,action,pending]=useActionState(createMember,undefined);return <form action={action} className="border rounded p-4 space-y-3"><h2 className="text-xl font-bold">إضافة موظف</h2><label className="block">البريد<input className="border p-2" type="email" name="email" required autoComplete="off"/></label><label className="block">كلمة مرور أولية<input className="border p-2" type="password" name="password" minLength={12} required autoComplete="new-password"/></label>{options.map(([id,label])=><label className="block" key={id}><input name="permissions" type="checkbox" value={id}/> {label}</label>)}{state?.message&&<p role={state.success?'status':'alert'}>{state.message}</p>}<button disabled={pending} className="border bg-blue-700 text-white p-2">إنشاء الموظف</button></form>;}

export function LinkMemberForm(){const[state,action,pending]=useActionState(linkExistingMember,undefined);return <form action={action} className="border rounded p-4 space-y-3"><h2 className="font-bold">ربط حساب دخول موجود</h2><input type="email" name="email" required placeholder="البريد الحالي" className="border p-2"/>{options.map(([id,label])=><label className="block" key={id}><input name="permissions" type="checkbox" value={id}/> {label}</label>)}{state?.message&&<p role={state.success?'status':'alert'}>{state.message}</p>}<button disabled={pending} className="border p-2">ربط كموظف</button></form>;}
